# Workflow profile for mkseurat

# Conda settings
use-conda: True
conda-frontend: mamba

# General settings
verbose: False
keep-going: True
rerun-incomplete: True
latency-wait: 30
retries: 0

# Resource settings per rule
set-resources:
  create_seurat_object:
    threads: 1
    mem: "8GB"
    runtime: 30
  merge_captures:
    threads: 16
    mem: "128GB"
    runtime: 60
  create_anndata_object:
    threads: 1
    mem: "8GB"
    runtime: 30
  merge_anndata_captures:
    threads: 16
    mem: "128GB"
    runtime: 60
